version: "3.9"

services:
  jupyter:
    container_name: ${CONTAINER_NAME}
    image: ${IMAGE_NAME}:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - jupyter
    ports:
      - "${PORT}:8888"
    volumes:
      - ./notebooks/:/home/jovyan/work
    user: root
    command: start.sh jupyter lab --LabApp.token=''

networks:
  jupyter:
